import{initializeApp}from"https://www.gstatic.com/firebasejs/12.7.0/firebase-app.js";
import{getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut}from"https://www.gstatic.com/firebasejs/12.7.0/firebase-auth.js";
import{getFirestore,collection,doc,onSnapshot,addDoc,setDoc,deleteDoc,serverTimestamp,query,orderBy,limit}from"https://www.gstatic.com/firebasejs/12.7.0/firebase-firestore.js";
import{firebaseConfig}from"./firebase-config.js";
import{TOTAL_TOMBOS,TOMBOS,TOMBO_SET}from"./base.js";

const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const $=s=>document.querySelector(s);
const loginView=$("#loginView"),mainView=$("#mainView"),loginForm=$("#loginForm"),loginMessage=$("#loginMessage"),logoutBtn=$("#logoutBtn"),userEmail=$("#userEmail");
const counter=$("#counter"),newCounter=$("#newCounter"),checkForm=$("#checkForm"),tomboInput=$("#tomboInput"),checkMessage=$("#checkMessage"),confirmBtn=$("#confirmBtn");
const listPanel=$("#listPanel"),listTitle=$("#listTitle"),listCount=$("#listCount"),itemsList=$("#itemsList");
const registerPanel=$("#registerPanel"),localInput=$("#localInput"),tipoInput=$("#tipoInput"),marcaInput=$("#marcaInput"),modeloInput=$("#modeloInput"),saveConfigBtn=$("#saveConfigBtn"),clearConfigBtn=$("#clearConfigBtn"),configList=$("#configList"),configCount=$("#configCount"),activeConfig=$("#activeConfig"),novoTomboInput=$("#novoTomboInput"),serialInput=$("#serialInput"),registerBtn=$("#registerBtn"),registerMessage=$("#registerMessage"),recentList=$("#recentList"),recentCount=$("#recentCount");
const newItemsPanel=$("#newItemsPanel"),newItemsList=$("#newItemsList"),newItemsListCount=$("#newItemsListCount");
const exportPanel=$("#exportPanel"),exportBtn=$("#exportBtn"),exportMessage=$("#exportMessage");

let conferidos=new Set(),novosEquipamentos=[],configuracoes=[],recentes=[],unsubConferencias=null,unsubNovos=null,unsubConfigs=null,currentView="check",tomboEncontrado=null,configSelecionada=null;

loginForm.addEventListener("submit",async e=>{e.preventDefault();loginMessage.textContent="Entrando...";loginMessage.className="message info";try{await signInWithEmailAndPassword(auth,$("#email").value.trim(),$("#password").value);loginForm.reset()}catch(err){loginMessage.textContent=authError(err);loginMessage.className="message error"}});
logoutBtn.onclick=()=>signOut(auth);

document.querySelectorAll("nav button").forEach(b=>b.addEventListener("click",()=>{currentView=b.dataset.view;document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x===b));render()}));

checkForm.addEventListener("submit",async e=>{e.preventDefault();const entrada=String(tomboInput.value).trim();tomboEncontrado=null;confirmBtn.classList.add("hidden");checkMessage.className="message";if(!/^\d{4}$/.test(entrada)){msg(checkMessage,"Digite exatamente os 4 últimos dígitos do tombo.","error");tomboInput.select();return}const candidatos=TOMBOS.filter(t=>t.endsWith(entrada));if(candidatos.length===0){msg(checkMessage,"Tombo não encontrado na base.","error");tomboInput.select();return}if(candidatos.length>1){msg(checkMessage,`Atenção: existem ${candidatos.length} tombos com esses 4 últimos dígitos.`,"error");tomboInput.select();return}const t=candidatos[0];if(conferidos.has(t)){msg(checkMessage,`Tombo ${t} já foi conferido anteriormente.`,"info");tomboInput.select();return}tomboEncontrado=t;msg(checkMessage,`Tombo encontrado: ${t}. Confirme abaixo para registrar a conferência.`,"success");confirmBtn.classList.remove("hidden")});

confirmBtn.addEventListener("click",async()=>{if(!tomboEncontrado||conferidos.has(tomboEncontrado))return;confirmBtn.disabled=true;try{await setDoc(doc(db,"conferencias",tomboEncontrado),{tombo:tomboEncontrado,conferidoEm:serverTimestamp(),conferidoPor:auth.currentUser.uid,email:auth.currentUser.email||""});msg(checkMessage,"Conferência confirmada e salva.","success");tomboEncontrado=null;confirmBtn.classList.add("hidden");tomboInput.value="";tomboInput.focus()}catch(err){console.error(err);msg(checkMessage,"Não foi possível salvar a conferência.","error")}finally{confirmBtn.disabled=false}});

saveConfigBtn.addEventListener("click",async()=>{const cfg=lerConfigFormulario();if(!cfg.tipo||!cfg.marca||!cfg.modelo){msg(registerMessage,"Informe Equipamento, Marca e Modelo para salvar uma configuração.","error");return}saveConfigBtn.disabled=true;try{const existente=configuracoes.find(c=>sameConfig(c,cfg));if(existente){configSelecionada=existente;renderConfigs();msg(registerMessage,"Essa configuração já existe e foi selecionada.","info");return}const ref=await addDoc(collection(db,"configuracoesCadastro"),{...cfg,criadaEm:serverTimestamp(),criadaPor:auth.currentUser.uid,email:auth.currentUser.email||""});configSelecionada={id:ref.id,...cfg};renderConfigs();msg(registerMessage,"Configuração salva e selecionada.","success")}catch(err){console.error(err);msg(registerMessage,"Não foi possível salvar a configuração.","error")}finally{saveConfigBtn.disabled=false}});

clearConfigBtn.addEventListener("click",()=>{configSelecionada=null;tipoInput.value="";marcaInput.value="";modeloInput.value="";renderConfigs();updateActiveConfig();msg(registerMessage,"Configuração limpa. Informe uma nova configuração.","info")});

registerBtn.addEventListener("click",async()=>{const cfg=lerConfigFormulario();const tombo=normalizarTombo(novoTomboInput.value);const serial=normalizarSerial(serialInput.value);if(!cfg.tipo||!cfg.marca||!cfg.modelo){msg(registerMessage,"Selecione ou informe uma configuração de Equipamento, Marca e Modelo.","error");return}if(!tombo.ok){msg(registerMessage,"O Tombo deve conter somente números ou N/A.","error");novoTomboInput.focus();return}if(!serial.ok){msg(registerMessage,"O Serial deve ser alfanumérico ou N/A.","error");serialInput.focus();return}if(tombo.value==="N/A"&&serial.value==="N/A"){msg(registerMessage,"Informe pelo menos o Tombo ou o Serial para cadastrar o equipamento.","error");novoTomboInput.focus();return}if(tombo.value!=="N/A"&&TOMBO_SET.has(tombo.value)){msg(registerMessage,"Este Tombo pertence à base original de 177 itens. Faça a conferência na tela principal.","error");novoTomboInput.focus();return}if(tombo.value!=="N/A"&&novosEquipamentos.some(x=>x.tombo===tombo.value)){msg(registerMessage,"Este Tombo já foi cadastrado entre os novos equipamentos.","error");novoTomboInput.focus();return}registerBtn.disabled=true;try{await addDoc(collection(db,"novosEquipamentos"),{local:localInput.value.trim(),tipo:cfg.tipo,marca:cfg.marca,modelo:cfg.modelo,tombo:tombo.value,serial:serial.value,cadastradoEm:serverTimestamp(),cadastradoPor:auth.currentUser.uid,email:auth.currentUser.email||""});msg(registerMessage,"Equipamento cadastrado com sucesso.","success");novoTomboInput.value="N/A";serialInput.value="N/A";novoTomboInput.focus()}catch(err){console.error(err);msg(registerMessage,"Não foi possível cadastrar o equipamento.","error")}finally{registerBtn.disabled=false}});

exportBtn.addEventListener("click",exportarExcel);

function lerConfigFormulario(){return{local:localInput.value.trim(),tipo:tipoInput.value.trim(),marca:marcaInput.value.trim(),modelo:modeloInput.value.trim()}}
function sameConfig(a,b){return norm(a.tipo)===norm(b.tipo)&&norm(a.marca)===norm(b.marca)&&norm(a.modelo)===norm(b.modelo)}
function norm(v){return String(v||"").trim().toLowerCase()}
function normalizarTombo(v){const x=String(v??"").trim();if(!x||x.toUpperCase()==="N/A")return{ok:true,value:"N/A"};return /^\d+$/.test(x)?{ok:true,value:x}:{ok:false,value:x}}
function normalizarSerial(v){const x=String(v??"").trim();if(!x||x.toUpperCase()==="N/A")return{ok:true,value:"N/A"};return /^[a-z0-9]+$/i.test(x)?{ok:true,value:x}:{ok:false,value:x}}
function msg(el,text,type){el.textContent=text;el.className=`message ${type||""}`}

function render(){
  registerPanel.classList.toggle("hidden",currentView!=="register");
  exportPanel.classList.toggle("hidden",currentView!=="export");
  newItemsPanel.classList.toggle("hidden",currentView!=="newItems");
  const listView=currentView==="done"||currentView==="pending";
  listPanel.classList.toggle("hidden",!listView);
  if(listView){const a=currentView==="done"?TOMBOS.filter(t=>conferidos.has(t)):TOMBOS.filter(t=>!conferidos.has(t));listTitle.textContent=currentView==="done"?"Conferidos":"Pendentes";listCount.textContent=a.length;itemsList.innerHTML=a.length?a.map(t=>`<li>${esc(t)}</li>`).join(""):"<li>Nenhum item nesta lista.</li>"}
  if(currentView==="newItems")renderNewItems();
  if(currentView==="register")renderConfigs();
}

function renderConfigs(){configCount.textContent=configuracoes.length;updateActiveConfig();if(!configuracoes.length){configList.innerHTML='<div class="empty">Nenhuma configuração salva.</div>';return}configList.innerHTML=configuracoes.map(c=>`<div class="config-item ${configSelecionada?.id===c.id?"active":""}" data-id="${escAttr(c.id)}"><div class="config-text"><strong>${esc(c.tipo)} · ${esc(c.marca)} · ${esc(c.modelo)}</strong><small>Configuração reutilizável</small></div><button type="button" data-delete-config="${escAttr(c.id)}">Excluir</button></div>`).join("");configList.querySelectorAll(".config-item").forEach(el=>el.addEventListener("click",e=>{if(e.target.closest("[data-delete-config]"))return;const c=configuracoes.find(x=>x.id===el.dataset.id);if(c){configSelecionada=c;tipoInput.value=c.tipo;marcaInput.value=c.marca;modeloInput.value=c.modelo;renderConfigs();msg(registerMessage,"Configuração selecionada. Agora informe Tombo e Serial.","info");novoTomboInput.focus()}}));configList.querySelectorAll("[data-delete-config]").forEach(btn=>btn.addEventListener("click",async e=>{e.stopPropagation();if(!confirm("Excluir esta configuração salva? Os equipamentos já cadastrados não serão apagados."))return;try{await deleteDoc(doc(db,"configuracoesCadastro",btn.dataset.deleteConfig));if(configSelecionada?.id===btn.dataset.deleteConfig)configSelecionada=null;msg(registerMessage,"Configuração excluída.","info")}catch(err){console.error(err);msg(registerMessage,"Não foi possível excluir a configuração.","error")}}))}
function updateActiveConfig(){if(configSelecionada){activeConfig.textContent=`Configuração ativa: ${configSelecionada.tipo} · ${configSelecionada.marca} · ${configSelecionada.modelo}${configSelecionada.local?` · ${configSelecionada.local}`:""}`}else{activeConfig.textContent="Nenhuma configuração selecionada."}}

function renderNewItems(){newItemsListCount.textContent=novosEquipamentos.length;if(!novosEquipamentos.length){newItemsList.innerHTML='<div class="empty">Nenhum equipamento cadastrado ainda.</div>';return}const rows=novosEquipamentos.map(x=>`<tr><td>${esc(x.local||"N/A")}</td><td>${esc(x.tipo)}</td><td>${esc(x.marca)}</td><td>${esc(x.modelo)}</td><td>${esc(x.tombo)}</td><td>${esc(x.serial)}</td><td>${esc(x.email||"")}</td></tr>`).join("");newItemsList.innerHTML=`<table class="data-table"><thead><tr><th>Local</th><th>Equipamento</th><th>Marca</th><th>Modelo</th><th>Tombo</th><th>Serial</th><th>Cadastrado por</th></tr></thead><tbody>${rows}</tbody></table>`}

async function exportarExcel(){exportBtn.disabled=true;msg(exportMessage,"Preparando arquivo...","info");try{const XLSX=await import("https://cdn.sheetjs.com/xlsx-0.20.3/package/xlsx.mjs");const original=TOMBOS.map(t=>({"Tombo Legado":t,"Situação":conferidos.has(t)?"Conferido":"Pendente"}));const novos=novosEquipamentos.map(x=>({"Local":x.local||"N/A","Equipamento":x.tipo,"Marca":x.marca,"Modelo":x.modelo,"Tombo":x.tombo,"Serial":x.serial,"Data do cadastro":formatTimestamp(x.cadastradoEm),"Cadastrado por":x.email||x.cadastradoPor||""}));const resumo=[{"Indicador":"Itens da relação original","Quantidade":TOTAL_TOMBOS},{"Indicador":"Itens originais conferidos","Quantidade":conferidos.size},{"Indicador":"Itens originais pendentes","Quantidade":TOTAL_TOMBOS-conferidos.size},{"Indicador":"Novos equipamentos cadastrados","Quantidade":novosEquipamentos.length},{"Indicador":"Total de equipamentos identificados","Quantidade":conferidos.size+novosEquipamentos.length}];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(resumo),"Resumo");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(original),"Conferencia Original");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(novos),"Novos Equipamentos");XLSX.writeFile(wb,`conferencia-patrimonial-${dataArquivo()}.xlsx`);msg(exportMessage,"Excel gerado com sucesso.","success")}catch(err){console.error(err);msg(exportMessage,"Não foi possível gerar o Excel. Verifique a conexão e tente novamente.","error")}finally{exportBtn.disabled=false}}
function formatTimestamp(v){if(!v)return"";if(typeof v.toDate==="function")return v.toDate().toLocaleString("pt-BR");return String(v)}
function dataArquivo(){return new Date().toISOString().slice(0,10)}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function escAttr(v){return esc(v)}
function authError(e){if((e.code||"").includes("invalid-credential"))return"E-mail ou senha inválidos.";if((e.code||"").includes("too-many-requests"))return"Muitas tentativas. Tente novamente mais tarde.";return"Não foi possível entrar. Verifique os dados."}

onAuthStateChanged(auth,user=>{[unsubConferencias,unsubNovos,unsubConfigs].forEach(fn=>{try{fn?.()}catch{}});unsubConferencias=unsubNovos=unsubConfigs=null;if(!user){conferidos=new Set();novosEquipamentos=[];configuracoes=[];configSelecionada=null;loginView.classList.remove("hidden");mainView.classList.add("hidden");return}loginView.classList.add("hidden");mainView.classList.remove("hidden");userEmail.textContent=user.email||"";
unsubConferencias=onSnapshot(collection(db,"conferencias"),snap=>{conferidos=new Set(snap.docs.map(d=>d.id.trim()).filter(t=>TOMBO_SET.has(t)));counter.textContent=`${conferidos.size}/${TOTAL_TOMBOS}`;render()});
unsubNovos=onSnapshot(query(collection(db,"novosEquipamentos"),orderBy("cadastradoEm","desc")),snap=>{novosEquipamentos=snap.docs.map(d=>({id:d.id,...d.data()}));newCounter.textContent=novosEquipamentos.length;recentes=novosEquipamentos.slice(0,8);recentCount.textContent=recentes.length;recentList.innerHTML=recentes.length?recentes.map(x=>`<div class="recent-item"><strong>${esc(x.tombo)} · ${esc(x.serial)}</strong><small>${esc(x.tipo)} · ${esc(x.marca)} · ${esc(x.modelo)}${x.local?` · ${esc(x.local)}`:""}</small></div>`).join(""):"<div class="empty">Nenhum equipamento cadastrado.</div>";render()});
unsubConfigs=onSnapshot(query(collection(db,"configuracoesCadastro"),orderBy("criadaEm","desc")),snap=>{configuracoes=snap.docs.map(d=>({id:d.id,...d.data()}));if(configSelecionada){configSelecionada=configuracoes.find(c=>c.id===configSelecionada.id)||null}renderConfigs()});
setTimeout(()=>tomboInput.focus(),100)});

if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(console.error));
